version: "3"

services:
  lighthouse1:
    cap_add:
      - NET_ADMIN
    volumes:
      - ../../out:/out
    build:
      context: .
      dockerfile: ./Dockerfile
    devices:
      - /dev/net/tun
    networks:
      testnetwork:
        ipv4_address: 10.1.0.100

  node1:
    cap_add:
      - NET_ADMIN
    volumes:
      - ../../out:/out
    build:
      context: .
      dockerfile: ./Dockerfile
    devices:
      - /dev/net/tun
    networks:
      testnetwork:
        ipv4_address: 10.1.0.102

  node2:
    cap_add:
      - NET_ADMIN
    volumes:
      - ../../out:/out
    build:
      context: .
      dockerfile: ./Dockerfile
    devices:
      - /dev/net/tun
    networks:
      testnetwork:
        ipv4_address: 10.1.0.103

networks:
  testnetwork:
    ipam:
      driver: default
      config:
        - subnet: 10.1.0.0/24
